### ISSUE TITLE
Limit error when query big tables

### ISSUE THREAD

**Issue by ChaunceyDong** [jshinonome/kola#1]
hi,

Thank you for public the repo. It helps a lot. 

I met a Error like
`QKolaError: Internal Server Error - "limit"`

when `q.sync("tbl")`

the `tbl `is a Kdb table with rows like 10,000,000

is there any way to unlimit the settings?

Thanks!

**Comment by jshinonome** [comment]
Hi, what is the size of the table, use `-22!tbl` to get the size.

**Comment by ChaunceyDong** [comment]
hi,

thx for the prompt responds

```
q)-22!tbl
22672823693
````

**Comment by jshinonome** [comment]
Unfortunately, the max size per IPC is 2,147,483,647. To support more than 2,147,483,647 requires extra work. I would suggest you to make multiple requests for the table.

https://www.timestored.com/kdb-guides/errors/limit

**Comment by jshinonome** [comment]
Going to release a new version to support IPC message up to 2TB this weekend.
