### ISSUE TITLE
Inquiry on Integrating Polars Function within kdb Kernel

### ISSUE THREAD

**Issue by ChaunceyDong** [jshinonome/kola#2]
Hi,

I am writing to inquire about the possibility of calling a Polars function from within a kdb kernel.

Here is a simple example

``` python
def polars_func( pl_df : polars.DataFrame) -> polars.DataFrame:
    return pl_df
```

The desired workflow in kdb would look like this:
```q
func_py: load_py_func[path];
tbl: select from bigtbl;
tbl2: func_py[tbl];
```

Could you please let me know if this integration is feasible and, if so, provide any guidance or hints on how to accomplish it?

Thanks,
Chuanlin

**Comment by jshinonome** [comment]
Hi Chuanlin,

The short answer is it is too complicated to get this work done.

First of all, you need to manage q object conversion within kdb kernel.
Which mean whenever you call a python function for q object, you have to
convert it to py object first. When something returns from py, you need to
convert it back to q object.

Secondly, it depends what language you want to use to build this feature.
It has to be c/c++ or rust. Let us say if you use rust, you need to
understand pyo3 first and then rust for kdb. I won’t recommend you take
either way, they are both going to be a big project.

If you have to call some py function, use IPC. This means to setup a python
server and kdb can connect to this server and exchange data and run python
code. This is much easier to implement, but still, you need to learn some
knowledge about server/network/IPC.

Hope this gives you some ideas.

Kind regards,
Jo Shinonome

**Comment by ChaunceyDong** [comment]
Hi Jo Shinonome,

Thank you for the detailed explanation. 

Would this be easier if I use Rust?

Let's say I define a func in Rust:
- input Polars df
- output Polars df

then in Kdb

```q
func_rust: load_rust[path];

// Example usage in kdb+
tbl2: func_rust[tbl];
```


Regards,
Chuanlin

**Comment by jshinonome** [comment]
Hi Chuanlin,

It is easier, but not as easy as you may think.

https://github.com/diamondrod/kdbplus

You need to create a c function in Rust. Refer to the above repo. When the
function is invoked, you need to convert the k object to a Polars object.
After manipulating the Polars object in Rust, you must convert it back to
the k object and return it.

Kind regards,
Jo Shinonome
