### ISSUE TITLE
Won't pip install inside a docker container on Apple Silicon

### ISSUE THREAD

**Issue by braaannigan** [jshinonome/kola#3]
Hi - thanks for your work on this package.

I can `pip install kola` when running on my machine. A couple of months ago I think I also installed it inside a container (on a linux-based mac).  However, when I try to install inside a container today on apple silicon (I tried with many versions e.g. 1.5.0, 1.4.1, 0.9.0) I get this message from uv which is running pip

`
0.118   × No solution found when resolving dependencies:
0.118   ╰─▶ Because kola==0.9.0 has no wheels with a matching Python implementation
0.118       tag and you require kola==0.9.0, we can conclude that your requirements
0.118       are unsatisfiable.
------
`

Or if I try to install directly with pip I get a different message but which I think is similar in practice
`
ERROR: Could not find a version that satisfies the requirement kola (from versions: none)
ERROR: No matching distribution found for kola
` 
MRE:
```Dockerfile
FROM python:3.11.9
RUN pip install kola
```

`
docker build -t kola-image:latest .
`

One thing that's changed since my last install is that I'm now on apple silicon. I updated docker to 3.12 and tried again. I also tried

```
pip install https://files.pythonhosted.org/packages/d9/21/a75d13cfa735a11032fd985a2c75c074b8ffb7dcb3f77e70e0d9d637cac5/kola-1.5.0-cp312-cp312-macosx_11_0_arm64.whl
```

and get "ERROR: kola-1.5.0-cp312-cp312-macosx_11_0_arm64.whl is not a supported wheel on this platform."

Again, kola installs fine if I run pip outside the container. All my other packages are also working fine inside/outside the container.

Any suggestions?

**Comment by unfixa1** [comment]
Docker may use a different architecture (such as x86_64 or arm64) on Apple Silicon, which may cause package compatibility issues.

You can consider replacing docker with a tool such as [servbay](servbay.com), which is suitable for your needs

**Comment by braaannigan** [comment]
Hi @jshinonome 

I've looked into this a bit more: the issue is that there is no wheel like this one for Polars:
polars-1.9.0-cp38-abi3-manylinux_2_24_aarch64.whl 
(Uploaded Oct 1, 2024 CPython 3.8+ manylinux: glibc 2.24+ ARM64)

This is distinct from the macosx because it allows linux-based processed (e.g. Docker) to run an ARM architectures.

I see there is a comment in the github workflows file: "# manylinux aarch64 openssl doesn't work"
(https://github.com/jshinonome/kola/blob/main/.github/workflows/release-python-other-os.yml)

Any idea what is going wrong here and if we can fix it?

**Comment by jshinonome** [comment]
Thanks for the details. kdb requires OpenSSL if ssl is enabled, and I don't have such requirement using aarch64, which means I am less likely spending time for this kind of os build.
